version: "3.9"
services:
  backend:
    build: .
    container_name: backendtaskai
    ports:
      - "5500:5500"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: dbtaskai
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redistaskai
    ports:
      - "6379:6379"

volumes:
  dbdata:
